#!/usr/bin/env python3
"""Convert a PNG image to a PROGMEM RGB565 C array compatible with TFT_eSPI.

Output matches the existing `src/media/images_*.h` convention:

    static const uint16_t <Name>[] PROGMEM = { 0xRRGGBBgg, ... };
    static const uint16_t <Name>Width  = <W>;
    static const uint16_t <Name>Height = <H>;

The RGB565 byte order matches `tft.setSwapBytes(true)` — that's how the rest
of the firmware renders, so don't change it without also flipping every
existing header.

Usage:
    python tools/png2rgb565.py --input art.png --name MinerScreen --output - \\
        >> src/media/images_320_240.h
    python tools/png2rgb565.py --input art.png --name MinerScreen \\
        --output src/media/images_320_240.h --append

Requires Pillow:
    pip install pillow
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:  # pragma: no cover - import error guidance
    sys.stderr.write(
        "Pillow is not installed. Install it with: pip install pillow\n"
    )
    raise


def pack_rgb565(r: int, g: int, b: int) -> int:
    """Pack 8-bit RGB into 16-bit RGB565."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def png_to_rgb565(path: Path) -> tuple[int, int, list[int]]:
    """Load *path* and return (width, height, list of RGB565 ints).

    Pixels with alpha < 128 are flattened to magenta (0xF81F) so the artist can
    spot accidentally-transparent regions during the review pass.
    """
    img = Image.open(path).convert("RGBA")
    width, height = img.size
    pixels = list(img.getdata())
    encoded: list[int] = []
    for r, g, b, a in pixels:
        if a < 128:
            encoded.append(0xF81F)  # magenta sentinel
        else:
            encoded.append(pack_rgb565(r, g, b))
    return width, height, encoded


def emit_header(name: str, width: int, height: int, data: list[int]) -> str:
    lines: list[str] = []
    lines.append(f"// {name} — {width}x{height} RGB565, generated by tools/png2rgb565.py")
    lines.append(f"static const uint16_t {name}Width  = {width};")
    lines.append(f"static const uint16_t {name}Height = {height};")
    lines.append(f"static const uint16_t {name}[] PROGMEM = {{")

    per_line = 12  # readable diff width
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")

    lines.append("};")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert PNG → RGB565 PROGMEM C array (NerdMiner_Craft format)."
    )
    parser.add_argument("--input", "-i", required=True, type=Path, help="Source PNG path.")
    parser.add_argument(
        "--name", "-n", required=True,
        help="C identifier for the array (e.g. MinerScreen, PickaxeFrame0).",
    )
    parser.add_argument(
        "--output", "-o", default="-",
        help="Destination file, or '-' for stdout (default).",
    )
    parser.add_argument(
        "--append", action="store_true",
        help="Append to the output file instead of replacing it.",
    )
    args = parser.parse_args()

    if not args.input.is_file():
        parser.error(f"input not found: {args.input}")
    if not args.name.isidentifier():
        parser.error(f"--name must be a valid C identifier: {args.name!r}")

    width, height, data = png_to_rgb565(args.input)
    rendered = emit_header(args.name, width, height, data)

    if args.output == "-":
        sys.stdout.write(rendered)
    else:
        mode = "a" if args.append else "w"
        with open(args.output, mode, encoding="utf-8") as fh:
            fh.write(rendered)

    sys.stderr.write(
        f"{args.input.name} → {args.name} ({width}x{height}, "
        f"{len(data) * 2} bytes PROGMEM)\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
